name: Main Pull Request
on:
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 🛎️
                uses: actions/checkout@v2.3.4 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
            -   name: Cache 🗃️
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Setup Node ⚙️
                uses: actions/setup-node@v2
                with:
                    node-version: '16'
            -   name: Install and Build 🔧 # This example project is built using yarn and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
                run: |
                    npm install
                    npm run build
